# Generated by Django 4.2.1 on 2023-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbase',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='commentbase',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='community',
            name='evaluated_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='community',
            name='published_count',
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in review', 'in review'), ('submitted', 'submitted'), ('rejected', 'rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=10),
        ),
    ]
