# Generated by Django 4.2.3 on 2023-07-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_communitymeta_status_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_post_images/'),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in review', 'in review'), ('rejected', 'rejected'), ('submitted', 'submitted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=10),
        ),
    ]
