# Generated by Django 4.2.3 on 2023-09-29 08:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blockpersonalmessage_emailverify_personalmessage_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('published', 'published'), ('in review', 'in review'), ('rejected', 'rejected')], max_length=255),
        ),
    ]
