# Generated by Django 4.2.1 on 2023-07-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('rejected', 'rejected'), ('in review', 'in review'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=10),
        ),
    ]
