# Generated by Django 4.2.1 on 2023-06-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_commentbase_dislikes_remove_commentbase_likes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='keywords',
            new_name='keywordstr',
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('in review', 'in review')], max_length=255),
        ),
    ]
