# Generated by Django 4.2.3 on 2023-09-29 09:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emailverify_unregistereduser_article_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('rejected by user', 'rejected by user'), ('published', 'published'), ('accepted', 'accepted'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('in review', 'in review')], max_length=255),
        ),
    ]
