# Generated by Django 4.2.1 on 2023-06-25 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_keywords_article_keywordstr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='keywordstr',
            new_name='keywords',
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('in review', 'in review'), ('rejected', 'rejected')], max_length=255),
        ),
    ]
