# Generated by Django 4.2.3 on 2023-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_socialpost_image_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('in review', 'in review'), ('submitted', 'submitted')], max_length=255),
        ),
    ]
