# Generated by Django 4.2.3 on 2023-07-25 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('submitted', 'submitted'), ('in review', 'in review'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
