# Generated by Django 4.2.3 on 2023-10-07 15:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emailverify_unregistereduser_article_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialpost',
            name='body',
            field=models.TextField(max_length=2000),
        ),
    ]
