# Generated by Django 4.2.3 on 2023-07-20 15:35

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_user_subscribe_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='articles_file'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_article_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='published_article_file'),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('in review', 'in review'), ('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], max_length=10),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='social_post_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='profile_images'),
        ),
    ]
