# Generated by Django 4.2.3 on 2023-07-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='communitymember',
            name='unique_admin_per_community',
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('in review', 'in review')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('approved', 'approved')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(fields=('community', 'user'), name='unique_admin_per_community'),
        ),
        migrations.AddConstraint(
            model_name='communitymember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_admin', True)), fields=('user', 'is_admin'), name='only_one_community_admin'),
        ),
    ]
