# Generated by Django 4.2.3 on 2023-10-08 06:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_emailverify_unregistereduser_article_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrequests',
            name='about',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='summary',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
