# Generated by Django 4.2.1 on 2023-07-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('accepted', 'accepted'), ('in review', 'in review'), ('submitted', 'submitted')], max_length=255),
        ),
    ]
