# Generated by Django 4.2.3 on 2023-10-10 07:15

import app.models
import cloudinary.models
from django.conf import settings
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_emailverify_unregistereduser_article_doi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('media', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name=app.models.message_media)),
                ('body', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_group', to='app.article')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_article_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'article_chat_message',
            },
        ),
    ]
