# Generated by Django 4.2.3 on 2023-08-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article_published_date_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentbase',
            name='Type',
            field=models.CharField(choices=[('review', 'Review'), ('decision', 'Decision'), ('comment', 'Comment'), ('blog', 'Blog'), ('video', 'Video'), ('discussion', 'Discussion')], default='comment', max_length=10),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('in review', 'in review'), ('submitted', 'submitted'), ('rejected', 'rejected'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=10),
        ),
    ]
