# Generated by Django 4.2.1 on 2023-07-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='parent_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app.article'),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('in review', 'in review'), ('submitted', 'submitted'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('approved', 'approved')], max_length=10),
        ),
    ]
