# Generated by Django 4.2.3 on 2023-10-15 03:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_emailverify_unregistereduser_article_doi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.TextField(),
        ),
    ]
