# Generated by Django 4.2.1 on 2023-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_article_parent_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentbase',
            name='border_impacts',
        ),
        migrations.RemoveField(
            model_name='commentbase',
            name='recommendations',
        ),
        migrations.RemoveField(
            model_name='commentbase',
            name='strength_weakness',
        ),
        migrations.RemoveField(
            model_name='commentbase',
            name='summary',
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('in review', 'in review'), ('submitted', 'submitted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=10),
        ),
    ]
