# Generated by Django 4.2.1 on 2023-07-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_socialpost_socialpostcomment_article_blocked_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('in review', 'in review'), ('rejected', 'rejected'), ('submitted', 'submitted'), ('accepted', 'accepted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('approved', 'approved'), ('pending', 'pending')], max_length=10),
        ),
    ]
