# Generated by Django 4.2.1 on 2023-09-22 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_commentbase_version_alter_commentbase_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('submitted', 'submitted'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('in review', 'in review')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('approved', 'approved'), ('pending', 'pending')], max_length=10),
        ),
        migrations.CreateModel(
            name='EmailVerify',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_verify',
            },
        ),
    ]
