# Generated by Django 4.2.1 on 2023-09-25 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_communitymeta_status_unregistereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('submitted', 'submitted'), ('in review', 'in review'), ('rejected', 'rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=10),
        ),
        migrations.AlterField(
            model_name='unregistereduser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
