# Generated by Django 4.2.1 on 2023-09-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_communitymeta_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymeta',
            name='status',
            field=models.CharField(choices=[('accepted', 'accepted'), ('in review', 'in review'), ('submitted', 'submitted'), ('rejected', 'rejected')], max_length=255),
        ),
        migrations.AlterField(
            model_name='communityrequests',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('pending', 'pending'), ('approved', 'approved')], max_length=10),
        ),
    ]
